const pokemonData = [
  {
    id: 1,
    name: "Bulbasaur",
    type: "Grass",
    hp: 45,
    maxHp: 45,
    attack: 49,
    defense: 49,
    spAtk: 65,
    spDef: 65,
    speed: 45,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
    moves: [
      { name: "Tackle", damage: 40, accuracy: 0.95, pp: 35, type: "Normal", category: "physical" },
      { name: "Vine Whip", damage: 45, accuracy: 1.0, pp: 25, type: "Grass", category: "physical" },
      { name: "Powder Powder", damage: 75, accuracy: 0.75, pp: 15, type: "Grass", category: "special" },
      { name: "Synthesis", damage: 0, accuracy: 1.0, pp: 5, type: "Grass", category: "status", heal: 50 },
    ],
  },
  {
    id: 4,
    name: "Charmander",
    type: "Fire",
    hp: 39,
    maxHp: 39,
    attack: 52,
    defense: 43,
    spAtk: 60,
    spDef: 50,
    speed: 65,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",
    moves: [
      { name: "Scratch", damage: 40, accuracy: 1.0, pp: 35, type: "Normal", category: "physical" },
      { name: "Ember", damage: 40, accuracy: 1.0, pp: 25, type: "Fire", category: "special" },
      { name: "Flame Burst", damage: 70, accuracy: 1.0, pp: 15, type: "Fire", category: "special" },
      { name: "Dragon Rage", damage: 0, accuracy: 0.9, pp: 10, type: "Dragon", category: "status", effect: "burn" },
    ],
  },
  {
    id: 7,
    name: "Squirtle",
    type: "Water",
    hp: 44,
    maxHp: 44,
    attack: 48,
    defense: 65,
    spAtk: 50,
    spDef: 64,
    speed: 43,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",
    moves: [
      { name: "Tackle", damage: 40, accuracy: 0.95, pp: 35, type: "Normal", category: "physical" },
      { name: "Water Gun", damage: 40, accuracy: 1.0, pp: 25, type: "Water", category: "special" },
      { name: "Hydro Pump", damage: 110, accuracy: 0.8, pp: 5, type: "Water", category: "special" },
      { name: "Protect", damage: 0, accuracy: 1.0, pp: 10, type: "Normal", category: "status", effect: "protect" },
    ],
  },
  {
    id: 25,
    name: "Pikachu",
    type: "Electric",
    hp: 35,
    maxHp: 35,
    attack: 55,
    defense: 40,
    spAtk: 50,
    spDef: 50,
    speed: 90,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
    moves: [
      { name: "Quick Attack", damage: 40, accuracy: 1.0, pp: 30, type: "Normal", category: "physical" },
      { name: "Thunder Shock", damage: 40, accuracy: 1.0, pp: 30, type: "Electric", category: "special" },
      { name: "Thunderbolt", damage: 90, accuracy: 1.0, pp: 15, type: "Electric", category: "special" },
      { name: "Thunder Wave", damage: 0, accuracy: 0.9, pp: 20, type: "Electric", category: "status", effect: "paralyze" },
    ],
  },
  {
    id: 39,
    name: "Jigglypuff",
    type: "Normal",
    hp: 115,
    maxHp: 115,
    attack: 45,
    defense: 20,
    spAtk: 45,
    spDef: 25,
    speed: 20,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png",
    moves: [
      { name: "Pound", damage: 40, accuracy: 1.0, pp: 35, type: "Normal", category: "physical" },
      { name: "Body Slam", damage: 85, accuracy: 1.0, pp: 15, type: "Normal", category: "physical" },
      { name: "Sing", damage: 0, accuracy: 0.55, pp: 15, type: "Normal", category: "status", effect: "sleep" },
      { name: "Dazzling Gleam", damage: 80, accuracy: 1.0, pp: 10, type: "Fairy", category: "special" },
    ],
  },
  {
    id: 52,
    name: "Meowth",
    type: "Normal",
    hp: 40,
    maxHp: 40,
    attack: 45,
    defense: 35,
    spAtk: 40,
    spDef: 40,
    speed: 90,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png",
    moves: [
      { name: "Scratch", damage: 40, accuracy: 1.0, pp: 35, type: "Normal", category: "physical" },
      { name: "Bite", damage: 60, accuracy: 1.0, pp: 25, type: "Dark", category: "physical" },
      { name: "Pay Day", damage: 40, accuracy: 1.0, pp: 20, type: "Normal", category: "physical" },
      { name: "Fury Swipes", damage: 18, accuracy: 0.8, pp: 15, type: "Normal", category: "physical" },
    ],
  },
  {
    id: 54,
    name: "Psyduck",
    type: "Water",
    hp: 50,
    maxHp: 50,
    attack: 52,
    defense: 48,
    spAtk: 65,
    spDef: 50,
    speed: 55,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png",
    moves: [
      { name: "Scratch", damage: 40, accuracy: 1.0, pp: 35, type: "Normal", category: "physical" },
      { name: "Water Gun", damage: 40, accuracy: 1.0, pp: 25, type: "Water", category: "special" },
      { name: "Confusion", damage: 50, accuracy: 1.0, pp: 25, type: "Psychic", category: "special", effect: "confuse" },
      { name: "Hydro Pump", damage: 110, accuracy: 0.8, pp: 5, type: "Water", category: "special" },
    ],
  },
  {
    id: 66,
    name: "Machop",
    type: "Fighting",
    hp: 70,
    maxHp: 70,
    attack: 80,
    defense: 50,
    spAtk: 35,
    spDef: 35,
    speed: 35,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png",
    moves: [
      { name: "Low Kick", damage: 50, accuracy: 1.0, pp: 20, type: "Fighting", category: "physical" },
      { name: "Focus Energy", damage: 0, accuracy: 1.0, pp: 30, type: "Normal", category: "status" },
      { name: "Karate Chop", damage: 50, accuracy: 1.0, pp: 25, type: "Fighting", category: "physical" },
      { name: "Seismic Toss", damage: 0, accuracy: 1.0, pp: 20, type: "Fighting", category: "physical" },
    ],
  },
  {
    id: 92,
    name: "Gastly",
    type: "Ghost",
    hp: 30,
    maxHp: 30,
    attack: 35,
    defense: 30,
    spAtk: 100,
    spDef: 35,
    speed: 80,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png",
    moves: [
      { name: "Lick", damage: 30, accuracy: 1.0, pp: 30, type: "Ghost", category: "physical", effect: "paralyze" },
      { name: "Spite", damage: 0, accuracy: 1.0, pp: 10, type: "Ghost", category: "status" },
      { name: "Shadow Ball", damage: 80, accuracy: 1.0, pp: 15, type: "Ghost", category: "special" },
      { name: "Dream Eater", damage: 100, accuracy: 1.0, pp: 15, type: "Psychic", category: "special" },
    ],
  },
  {
    id: 104,
    name: "Cubone",
    type: "Ground",
    hp: 50,
    maxHp: 50,
    attack: 75,
    defense: 85,
    spAtk: 20,
    spDef: 30,
    speed: 35,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png",
    moves: [
      { name: "Bone Club", damage: 65, accuracy: 0.85, pp: 20, type: "Ground", category: "physical" },
      { name: "Tail Whip", damage: 0, accuracy: 1.0, pp: 30, type: "Normal", category: "status" },
      { name: "Earthquake", damage: 100, accuracy: 1.0, pp: 10, type: "Ground", category: "physical" },
      { name: "Focus Blast", damage: 120, accuracy: 0.7, pp: 5, type: "Fighting", category: "special" },
    ],
  },
  {
    id: 133,
    name: "Eevee",
    type: "Normal",
    hp: 55,
    maxHp: 55,
    attack: 55,
    defense: 50,
    spAtk: 45,
    spDef: 65,
    speed: 55,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png",
    moves: [
      { name: "Tackle", damage: 40, accuracy: 0.95, pp: 35, type: "Normal", category: "physical" },
      { name: "Tail Whip", damage: 0, accuracy: 1.0, pp: 30, type: "Normal", category: "status" },
      { name: "Bite", damage: 60, accuracy: 1.0, pp: 25, type: "Dark", category: "physical" },
      { name: "Swift", damage: 60, accuracy: 1.0, pp: 20, type: "Normal", category: "special" },
    ],
  },
  {
    id: 143,
    name: "Snorlax",
    type: "Normal",
    hp: 150,
    maxHp: 150,
    attack: 110,
    defense: 65,
    spAtk: 65,
    spDef: 110,
    speed: 30,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png",
    moves: [
      { name: "Body Slam", damage: 85, accuracy: 1.0, pp: 15, type: "Normal", category: "physical" },
      { name: "Crunch", damage: 80, accuracy: 1.0, pp: 15, type: "Dark", category: "physical" },
      { name: "Rest", damage: 0, accuracy: 1.0, pp: 10, type: "Psychic", category: "status", heal: 100 },
      { name: "Earthquake", damage: 100, accuracy: 1.0, pp: 10, type: "Ground", category: "physical" },
    ],
  },
  {
    id: 147,
    name: "Dratini",
    type: "Dragon",
    hp: 41,
    maxHp: 41,
    attack: 64,
    defense: 45,
    spAtk: 50,
    spDef: 50,
    speed: 50,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png",
    moves: [
      { name: "Wrap", damage: 15, accuracy: 0.9, pp: 20, type: "Normal", category: "physical" },
      { name: "Dragon Breath", damage: 60, accuracy: 1.0, pp: 20, type: "Dragon", category: "special" },
      { name: "Dragon Rage", damage: 0, accuracy: 0.9, pp: 10, type: "Dragon", category: "status" },
      { name: "Aqua Tail", damage: 90, accuracy: 0.9, pp: 10, type: "Water", category: "physical" },
    ],
  },
  {
    id: 151,
    name: "Mew",
    type: "Psychic",
    hp: 100,
    maxHp: 100,
    attack: 100,
    defense: 100,
    spAtk: 100,
    spDef: 100,
    speed: 100,
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png",
    moves: [
      { name: "Psychic", damage: 90, accuracy: 1.0, pp: 10, type: "Psychic", category: "special" },
      { name: "Fire Punch", damage: 75, accuracy: 1.0, pp: 15, type: "Fire", category: "physical" },
      { name: "Ice Punch", damage: 75, accuracy: 1.0, pp: 15, type: "Ice", category: "physical" },
      { name: "Thunder Punch", damage: 75, accuracy: 1.0, pp: 15, type: "Electric", category: "physical" },
    ],
  },
];

// Type effectiveness chart
export const typeChart = {
  Normal: { super: [], weak: ["Fighting"], resist: [] },
  Fire: { super: ["Grass", "Ice", "Bug", "Steel"], weak: ["Water", "Ground", "Rock"], resist: ["Fire", "Grass", "Ice", "Bug", "Steel", "Fairy"] },
  Water: { super: ["Fire", "Ground", "Rock"], weak: ["Electric", "Grass"], resist: ["Fire", "Water", "Ice", "Steel"] },
  Electric: { super: ["Water", "Flying"], weak: ["Ground"], resist: ["Electric", "Flying", "Steel"] },
  Grass: { super: ["Water", "Ground", "Rock"], weak: ["Fire", "Ice", "Poison", "Flying", "Bug"], resist: ["Ground", "Water", "Grass", "Electric"] },
  Ice: { super: ["Flying", "Ground", "Grass", "Dragon"], weak: ["Fire", "Fighting", "Rock", "Steel"], resist: ["Ice"] },
  Fighting: { super: ["Normal", "Ice", "Rock", "Dark", "Steel"], weak: ["Flying", "Psychic", "Fairy"], resist: ["Rock", "Bug", "Dark"] },
  Poison: { super: ["Grass", "Fairy"], weak: ["Ground", "Psychic"], resist: ["Fighting", "Poison", "Bug", "Grass"] },
  Ground: { super: ["Fire", "Electric", "Poison", "Rock", "Steel"], weak: ["Water", "Grass", "Ice"], resist: ["Poison", "Rock"] },
  Flying: { super: ["Fighting", "Bug", "Grass"], weak: ["Electric", "Ice", "Rock"], resist: ["Fighting", "Bug", "Grass"] },
  Psychic: { super: ["Fighting", "Poison"], weak: ["Bug", "Ghost", "Dark"], resist: ["Fighting", "Psychic"] },
  Bug: { super: ["Grass", "Psychic", "Dark"], weak: ["Fire", "Flying", "Rock"], resist: ["Fighting", "Ground", "Grass"] },
  Rock: { super: ["Fire", "Ice", "Flying", "Bug"], weak: ["Water", "Grass", "Fighting", "Ground", "Steel"], resist: ["Normal", "Flying", "Poison"] },
  Ghost: { super: ["Ghost", "Psychic"], weak: ["Ghost", "Dark"], resist: ["Poison", "Bug"] },
  Dragon: { super: ["Dragon"], weak: ["Ice", "Dragon", "Fairy"], resist: ["Fire", "Water", "Electric", "Grass"] },
  Dark: { super: ["Ghost", "Psychic"], weak: ["Fighting", "Bug", "Fairy"], resist: ["Ghost", "Dark"] },
  Steel: { super: ["Ice", "Rock", "Fairy"], weak: ["Fire", "Water", "Ground"], resist: ["Normal", "Flying", "Rock", "Bug", "Steel", "Grass", "Psychic", "Ice", "Dragon", "Fairy"] },
  Fairy: { super: ["Fighting", "Dragon", "Dark"], weak: ["Poison", "Steel"], resist: ["Fighting", "Bug"] },
};

export default pokemonData;
